# примеры API-запросов

@baseUrl = http://127.0.0.1:8080/api/v1

# создание продукта
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "onion3",
  "description": "Best onion!"
}

###

# получение продуктов
GET {{baseUrl}}/products/
Content-Type: application/json

###

# обновление продукта
PATCH {{baseUrl}}/products/5/
Content-Type: application/json

{
  "description": "Огурейчики"
}

###

# удаление продукта
DELETE http://127.0.0.1:8000/api/v1/products/5/
Content-Type: application/json

###

# поиск продуктов по названию и описанию
GET {{baseUrl}}/products/?search=огур
Content-Type: application/json

###

GET http://127.0.0.1:8000/api/v1/stocks/
Content-Type: application/json

###

# создание склада
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "address": "мой адрес_2",
  "positions": [
    {
      "product": 2,
      "quantity": 250,
      "price": 120.50
    }
  ]
}

###

# обновляем записи на складе
PATCH {{baseUrl}}/stocks/41/
Content-Type: application/json

{
  "positions": [
    {
      "product": 2,
      "quantity": 27,
      "price": 12.50
    },
    {
      "product": 1,
      "quantity": 202,
      "price": 10.50
    },
    {
      "product": 8,
      "quantity": 3,
      "price": 1.50
    }
  ]
}

###

# поиск складов, где есть определенный продукт
GET {{baseUrl}}/stocks/?products=2
Content-Type: application/json